export const GET_BRANDS = 'GET_BRANDS'
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS'
export const GET_BRANDS_FAILURE = 'GET_BRANDS_FAILURE'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const UPDATE_FILTERS='UPDATE_FILTERS'